### PR TITLE
feat(standardization): updated parameters for standardization

### PR DESCRIPTION
**Pull request by webark**
The other preprocessors such as `broccoli-less-single`, `broccoli-stylus-single`, and `broccoli-sass-source-maps`. only pass in 4 parameters. In order to move toward standardization of the different processing plugins, I believe it would help if this plugin only used 4 parameters as well. 

I added support for existing usages, but included a warning message so that the upgrade story is more "frictionless".

### CODE REVIEW

**Comment by webark** [comment]
@jeffjewiss what do you think about this modification?

**Comment by jeffjewiss** [comment]
@webark thanks for putting this together! I'm definitely for these changes and think it's a great idea to standardize how the various broccoli processors work.

I'd like to review the changes a bit more, as I saw a couple small things that I'd like to tweak, but I won't have time until after the weekend. If you don't mind waiting until then, we'll get this sorted out and merged. Thanks!

**Comment by webark** [comment]
@jeffjewiss no worries at all!! Just wanted to make sure you saw it :)

**Comment by jeffjewiss** [comment]
Hey @webark, sorry I took forever to get to this. I'm going to go ahead and merge this, and continue to make changes to work towards standardized parameters. Thanks again!

**Pull request merged**
