### PR TITLE
fix missing caching options

### PR DESCRIPTION
**Pull request by ezpuzz**
allows configuring `cacheInclude` or `cacheExclude` with reasonable default value

this will at least prevent running Postcss on `hbs` file changes if I understand correctly.

### CODE REVIEW

**Comment by ezpuzz** [comment]
also allowing user to specify for example that only `tailwind.config.js` should trigger rebuild may help https://github.com/jeffjewiss/ember-cli-postcss/issues/277

**Comment by jeffjewiss** [comment]
Thanks for this! Is the `cacheInclude` option from `broccoli-caching-writer`?

Do you think the default should maybe include only CSS related files (.css, .scss, .etc) and the readme could include instructions on how to add a regex for JS files or a specific file like `tailwind.config.js`? I wonder if ignoring `js` by default would provide better caching for most users.

**Comment by ezpuzz** [comment]
here is what is working best for me at the moment:

```
    postcssOptions: {
      compile: {
        cacheInclude: [/\.css$/, /.*tailwind.*/],
        map: false,
        plugins: [
          {
            module: require("postcss-import"),
            options: {
              path: ["node_modules"],
            },
          },
          {
            module: require("tailwindcss"),
            options: {
              config: "./app/styles/tailwind.js",
            },
          },
        ],
      }
    },
```

ignoring `js` would be better performance (already ignoring `hbs` with these defaults) but thinking about it more any `cacheInclude` value is going to be a breaking change.  for example if using purgecss no longer running on hbs changes will not purge until css is touched.

**Comment by ezpuzz** [comment]
i've updated the defaults

**Comment by jeffjewiss** [comment]
Thanks for this and for updating the defaults. I'm going to make a couple of other small changes before releasing a major version. Cheers.

**Comment by jeffjewiss** [comment]
@ezpuzz thanks for your help with this. Just wanted to give you a heads up that I've released version 4.0 of this package which contains the cache options.

I've tested it against a known project with slow incremental builds and this change is a big improvement. Cheers.

**Comment by ezpuzz** [comment]
@jeffjewiss glad to hear it!  thanks for your work.

**Pull request merged**
